name: CI

on:
  push:
    branches:
      - develop
      - main
      - release/*
  pull_request:
    branches:
      - develop
      - main
      - release/*

jobs:
  build_and_test_debug_gcc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure project
      run: cmake --preset debug-gcc

    - name: Build project
      run: cmake --build --preset debug-gcc

    - name: Run tests
      run: ctest --preset debug-gcc

  build_and_test_debug_clang:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure project
      run: cmake --preset debug-clang

    - name: Build project
      run: cmake --build --preset debug-clang

    - name: Run tests
      run: ctest --preset debug-clang
